services:
  api:
    build:
      context: .
      dockerfile: "Dockerfile.txt"
    ports:
      - "9999:9999"
    env_file:
      - .env
    environment:
      DATABASE_HOST: 'db'
    depends_on:
      - db

  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}  
    ports:
      - "5432:5432"
