name: software-engineering-lab-9

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Docker Compose
        run: |
          docker compose up -d --build
        env:
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb

      - name: Run Django unit tests
        run: |
          docker compose exec api python SEList4/manage.py test SEList4/myapp/tests || exit 1

  docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate API documentation
        run: |
          source venv/bin/activate
          python SEList4/manage.py generateschema > docs.json

      - name: Clean up unnecessary files
        run: |
          find . -name "__pycache__" -type d -exec rm -r {} +
          find . -name "*.pyc" -type f -delete

      - name: Commit and push documentation
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs.json
          git commit -m "Updated documentation" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
